appName: myhelmapp

port: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: devopsjourney1/mywebapp

resources:
  requests:
    memory: "256Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"
